language: node_js

node_js:
  - "6.9.2"

before_install:
  - npm i -g npm@3.10.9

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage